### ISSUE TITLE
note 8.4.0 npm 5.3.0 windows8.1  npm run dev 报错。

### ISSUE THREAD

**Issue by tryrefine** [zkboys/zk-react-template-management#1]
能否留个 qq 方便交流？或者创建一个 qq 群
---------
部分报错如下：
`ERROR in ./~/_zk-tookit@0.0.57@zk-tookit/redux/index.js
Module parse failed: D:\dev.workspace\antd-react\react-antd-redux-webpack-es6-spa-boilerplate\node_modules\_zk-tookit@0.0.57@zk-tookit\redux\index.js Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
| export * as actionTypes from './action-types';
| export * as actionPage from './action-page';
| export actionUtils from './action-utils';
 @ ./src/redux/store/configure-store.js 14:14-40
 @ ./src/App.jsx
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx

ERROR in ./~/_zk-tookit@0.0.57@zk-tookit/react/index.js
Module parse failed: D:\dev.workspace\antd-react\react-antd-redux-webpack-es6-spa-boilerplate\node_modules\_zk-tookit@0.0.57@zk-tookit\react\index.js Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
| export domEvent from './dom-event-hoc';
| export ajax from './promise-ajax-hoc';
| export event from './event-hoc';
 @ ./src/frame/Frame.jsx 30:14-40
 @ ./src/route/Router.jsx
 @ ./src/App.jsx
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx

ERROR in ./~/_zk-tookit@0.0.57@zk-tookit/antd/index.js
Module parse failed: D:\dev.workspace\antd-react\react-antd-redux-webpack-es6-spa-boilerplate\node_modules\_zk-tookit@0.0.57@zk-tookit\antd\index.js Unexpected token (1:9)
You may need an appropriate loader to handle this file type.
| export * as FormUtil from './form-util/FormUtils';
| export EditableCell from './editable-cell/EditableCell';
| export FontIcon from './font-icon/FontIcon';
 @ ./src/pages/home/Home.jsx 18:12-37
 @ ./src/route/Router.jsx
 @ ./src/App.jsx
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx

ERROR in ./src/commons/index.js
Module not found: Error: Can't resolve 'zk-tookit/axios' in 'D:\dev.workspace\antd-react\react-antd-redux-webpack-es6-spa-boilerplate\src\commons'
 @ ./src/commons/index.js 25:13-39
 @ ./src/App.jsx
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx

ERROR in ./src/commons/index.js
Module not found: Error: Can't resolve 'zk-tookit/axios/react-hoc' in 'D:\dev.workspace\antd-react\react-antd-redux-webpack-es6-spa-boilerplate\src\commons'
 @ ./src/commons/index.js 29:16-52
 @ ./src/App.jsx
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.48 MB       0
Child html-webpack-plugin for "login.html":
         Asset     Size  Chunks  Chunk Names
    login.html  1.48 MB       0
webpack: Failed to compile.`

**Comment by zkboys** [comment]
升级zk-tookit到最新版本可以解决这个问题（推荐使用yarn）：
`yarn upgrade zk-tookit` 或者 `npm update zk-tookit --save`

zk-tookit 原先在本地调试的，忘记更新了。

**Comment by zkboys** [comment]
QQ群已创建，667271903，欢迎入坑！
