### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by zhi3210happy** [zkboys/zk-react-template-management#2]
```
ERROR in ./~/_zk-tookit@0.0.60@zk-tookit/utils/tree-utils.js
Module parse failed: C:\Users\Administrator\Desktop\react-antd-redux-webpack-es6-spa-boilerplate-master\node_modules\_zk-tookit@0
.0.60@zk-tookit\utils\tree-utils.js Unexpected token (17:12)
You may need an appropriate loader to handle this file type.
|  */
| export function generateTreeNode(data, keyField = 'id', titleField = 'name') {
|     return {...data, title: data[titleField], key: data[keyField]};
| }
|
 @ ./src/App.jsx 29:17-54
 @ multi ./builder/dev-client babel-polyfill ./src/App.jsx
```

**Comment by zkboys** [comment]
你应该是使用npm 或者 cnpm 进行依赖的安装，我最近才发现的问题，npm 或 cnpm 安装之后，无法启动，只能使用yarn进行依赖安装。你将所有的依赖都删除，重新使用yarn安装试试。

**Comment by zhi3210happy** [comment]
一开始就是用的yarn 结果卡在1036/1037 不动
ck-es6-spa-boilerplate-master>yarn install
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
█████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
███████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░
███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░
█████████████████████░░░░░░░░░░░░░░░░░░░░░░░
███████████████████████░░░░░░░░░░░░░░░░░░░░░
█████████████████████████░░░░░░░░░░░░░░░░░░░
███████████████████████████░░░░░░░░░░░░░░░░░
██████████████████████████████░░░░░░░░░░░░░░
████████████████████████████████░░░░░░░░░░░░
████████████████████████████████████░░░░░░░░
███████████████████████████████████████░░░░░
██████████████████████████████████████████░░
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
████████████████████████████████████████████
██████████████████████████████████ 1036/1037

**Comment by zkboys** [comment]
应该是你的网络环境问题，翻墙试试
